### ISSUE TITLE
backup.php - Backup page blank with PHP 7.2

### ISSUE THREAD

**Issue by Leuchtturm123** [gOOvER/ts3webinterface#1] opened 2018-01-04 09:38 UTC
After upgrading to PHP 7.2 backup channel page is blank and backup server page shows no past backups.

I changed the code in backup.php that a backup will be done but you can not see it listed on the page and no blank channel page anymore.

Can anybody help me how it can be fixed to see recent backups again?

Line 99:

```
$handler=opendir("site/backups/channel/");
while($datei=readdir($handler))
	{
	if($datei!='.' AND $datei!='..' AND $datei!='hostbackups')
		{
		$datei=str_replace('.txt', '', $datei);
		$datei_info=explode('_', $datei);
		$files=array(); //NEW CODE
		$files[0][]=array("timestamp"=>$datei_info[1], "server"=>$datei_info[2]);
		}
	}	

$handler=opendir("site/backups/channel/hostbackups/");
while($datei=readdir($handler))
	{
	if($datei!='.' AND $datei!='..')
		{
		$datei=str_replace('.txt', '', $datei);
		$datei_info=explode('_', $datei);
		$files=array(); //NEW CODE
		$files[1][]=array("timestamp"=>$datei_info[1], "server"=>$datei_info[2]);
		}
	}
```

**Comment by chaos234** [comment] 2018-01-10 09:01
The answere is simply, remove your changes in /site/backup.php as this is causing the problem.
You only have to change Line 20 from "files='';" to "$files=array();".

Your changes seems to permanently overwrite the files array in php 7.2 which causes that files ar not appearing.

```
<?php 
/*
*Copyright (C) 2012-2013  Psychokiller
*
*This program is free software; you can redistribute it and/or modify it under the terms of 
*the GNU General Public License as published by the Free Software Foundation; either 
*version 3 of the License, or any later version.
*
*This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
*without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
*See the GNU General Public License for more details.
*
*You should have received a copy of the GNU General Public License along with this program; if not, see <http://www.gnu.org/licenses/>. 
*/
if(!defined("SECURECHECK")) {die($lang['error_file_alone']);} 
if($sid===false OR empty($sid)) { echo "<meta http-equiv=\"refresh\" content=\"0; URL=index.php?site=server\">";} else {

$error='';
$noerror='';
$files=array();
```

**Comment by chaos234** [comment] 2018-01-10 09:12
You should also change this in sites/iserverbackup.php (to prevent this bug) und sites/serverbackup.php (same bug like with sites/backup.php)

For sites/iserverbackup.php change line 29 and for sites/serverbackup.php change line 28 like stated in the comment above and all will work fine :)

**Comment by Leuchtturm123** [comment] 2018-01-12 14:48
Thank you Chaos for your advise.
Changed all three files and it works as intended. 
Admininterface is now compatible with PHP 7.2

Will you update all three files in code section too?

**Comment by chaos234** [comment] 2018-01-12 14:59
I could make a PR here but I am not sure if this will get merged, since Psychokiller hasn't responded
yet.

So I am not sure when this gets applied then.

Am 12.01.2018 15:56:08 schrieb Leuchtturm123 <notifications@github.com>:
Thank you Chaos for your advise.
Changed all three files and it works as intended.
Admininterface is now compatible with PHP 7.2
Will you update all three files in code section too?

**Comment by gOOvER** [comment] 2018-01-12 15:43
i merged all PR's

**Comment by Leuchtturm123** [comment] 2018-01-12 15:43
Perfect. Thank you very much!

**Comment by chaos234** [comment] 2018-01-16 21:48
@Leuchtturm123 Would u pls release another PR which @gOOvER can fix then with the same changes to the other announced files (if not changed by @gOOvER already)?

This would fix/prevent the same problem at the described placed too ;)

**Comment by Leuchtturm123** [comment] 2018-01-16 22:23
We already updated all three mentioned files
________________________________

**Comment by chaos234** [comment] 2018-01-16 22:52
Ok, then this issiue can be closed.

**Closed** 2018-01-16 22:53 UTC
